/*
 * Copyright (c) 2024.
 *
 * This file is part of UFP project. UFP is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation either version 3 of the License, or (at your option) any later version.
 * UFP is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License along with UFP. If not, see <https://www.gnu.org/licenses/>.
 *
 */

-- liquibase formatted sql

-- changeset miroslav.mamrak:1712849461765-1
CREATE SEQUENCE IF NOT EXISTS board_entity_seq START WITH 1 INCREMENT BY 50;

-- changeset miroslav.mamrak:1712849461765-2
CREATE SEQUENCE IF NOT EXISTS post_entity_seq START WITH 1 INCREMENT BY 50;

-- changeset miroslav.mamrak:1712849461765-3
CREATE SEQUENCE IF NOT EXISTS user_entity_seq START WITH 1 INCREMENT BY 50;

-- changeset miroslav.mamrak:1712849461765-4
CREATE TABLE board_entity
(
    board_id BIGINT NOT NULL,
    CONSTRAINT pk_boardentity PRIMARY KEY (board_id)
);

-- changeset miroslav.mamrak:1712849461765-5
CREATE TABLE post_entity
(
    post_id                BIGINT NOT NULL,
    thread_entity_threadid BIGINT,
    image                  OID,
    CONSTRAINT pk_postentity PRIMARY KEY (post_id)
);

-- changeset miroslav.mamrak:1712849461765-6
CREATE TABLE thread_entity
(
    threadid               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    thread_name            VARCHAR(255),
    thread_description     VARCHAR(255),
    title                  VARCHAR(255)                            NOT NULL,
    creator_userid         BIGINT                                  NOT NULL,
    creation_timestamp     TIMESTAMP WITHOUT TIME ZONE,
    last_updated_timestamp TIMESTAMP WITHOUT TIME ZONE,
    content                ${LOBSTRING.TYPE},
    sticky_flag            BOOLEAN,
    locked_flag            BOOLEAN,
    archive_flag           BOOLEAN,
    view_count             INTEGER,
    boardid                BIGINT,
    CONSTRAINT pk_threadentity PRIMARY KEY (threadid)
);

-- changeset miroslav.mamrak:1712849461765-7
CREATE TABLE user_entity
(
    id                   BIGINT                      NOT NULL,
    "user-account-name"  VARCHAR(255)                NOT NULL,
    "user-display-name"  VARCHAR(255)                NOT NULL,
    password             VARCHAR(255)                NOT NULL,
    email                VARCHAR(255)                NOT NULL,
    city                 VARCHAR(255),
    country              VARCHAR(255),
    role                 VARCHAR(255)                NOT NULL,
    status               VARCHAR(255),
    "creation-date"      date                        NOT NULL,
    "creation-timestamp" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "last-updated-date"  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_userentity PRIMARY KEY (id)
);

-- changeset miroslav.mamrak:1712849461765-8
ALTER TABLE post_entity
    ADD CONSTRAINT FK_POSTENTITY_ON_THREAD_ENTITY_THREADID FOREIGN KEY (thread_entity_threadid) REFERENCES thread_entity (threadid);

